### PR TITLE
Create typedefs for SharedPtr, ConstSharedPtr

### PR DESCRIPTION
**Pull request by scpeters**
This will match the new typedef's in ros2:
https://github.com/ros2/design/pull/53

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The patch looks good.

But I won't merge this now. Before this needs to be fully agreed on in the ROS 2 discussion and for the migration path it must be clear that it is useful. Currently with the include path as well as the namespace being different it is only of limited use.

**Comment by scpeters** [comment]
Fair enough. If you prefer, feel free to close it until the time that it is ready.

**Comment by wjwwood** [comment]
+1. I'd say leave it open.

**Comment by scpeters** [comment]
Should we still leave this open or close it?

**Comment by dirk-thomas** [comment]
I will close this since nobody is planning to work on this. Please feel free to comment on the closed ticket and it can be reopened if necessary.

**Pull request closed without merging**
