### PR TITLE
Bug Fix rate inverting duration

### PR DESCRIPTION
**Pull request by lgerardSRI**
When constructing a Rate object with a duration as argument, it is the expected period duration, not a frequency.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thank you for making the pull request. Could you please also add a simple unit test covering this case?

This needs to be backported into all current ROS distros.

**Comment by lgerardSRI** [comment]
Yes I am quite surprised that it went unnoticed for all that time.
Do you need me to do something for the backporting?
I am writing a simple unittest.

**Comment by dirk-thomas** [comment]
No, for backporting I will just cherry-pick the commit once it has been released to the latest distro and has no regression.

Thanks for working on the unittest

**Comment by dirk-thomas** [comment]
Please squash your commits into a single one.

**Comment by lgerardSRI** [comment]
I did squash them (see the second commit attached to this report).
Please note that I haven't tested these changes, I don't have access to ROS on my mac.

**Comment by dirk-thomas** [comment]
The PR contains two commits. Please run `git rebase -i HEAD~2` and mark the second commit for squashing. Then the PR should only contain a single commit.

**Comment by lgerardSRI** [comment]
ok, the github web interface was tricking me, sorry.

**Comment by dirk-thomas** [comment]
Have you tried to compile the code? I get:

```
error: variable ‘ros::Rate r’ has initializer but incomplete type
```

**Comment by lgerardSRI** [comment]
No... see my comment above.
I am not working with ROS sources, this is a proposed code that I edited here on github.
It tricked me into doing this forking automatically etc, I should have just reported a plain bug.

**Comment by dirk-thomas** [comment]
Thanks - manually merged in 9198a8c45e4a58a14e5b5b693d2d97a0ca8936fc.

**Comment by trainman419** [comment]
Is it possible to get this backported to Hydro? I'm running into it while trying to initialize a rate from an interval.

It looks like this hasn't caused any regressions in Indigo.

**Comment by dirk-thomas** [comment]
Sounds viable to me. I will put it on "the list' for the next Hydro patch release round.

**Comment by dirk-thomas** [comment]
Backported to Hydro: 0.4.4

**Pull request closed without merging**
