### PR TITLE
fix #86.

### LINKED ISSUE #86: the destructor of DurationBase is not virtual
See the code

https://github.com/ros/roscpp_core/blob/d2bb8cbcfd4944e48d16cdb20edfab5d225db265/rostime/include/ros/duration.h#L79

https://github.com/ros/roscpp_core/blob/d2bb8cbcfd4944e48d16cdb20edfab5d225db265/rostime/include/ros/duration.h#L108

### PR DESCRIPTION
**Pull request by csukuangfj**
Fix #86.

### CODE REVIEW

**Comment by csukuangfj** [comment]
@dirk-thomas 
Could you please have a look at the test failure?
http://build.ros.org/job/Kpr__roscpp_core__ubuntu_xenial_amd64/46/testReport/

**Comment by dirk-thomas** [comment]
I think changing the destructor to be virtual would break ABI compatibility. Therefore this can only be considered for future distributions but can't be released into existing distributions.

**Comment by cwecht** [comment]
Changing the destructor to be virtual will introduce a vtable and a vptr to the class. On a 64-bit-machine the objects size will be doubled.

`ros::DurationBase` is an example for the [Curiously recurring template pattern](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern), which is a technique to implement static polymorphism.

I'd rather argue that `ros::DurationBase`s desctuctor should be removed entirely , which would make it trivially copyable (see also  #82). But this will also result in an ABI-break.

**Comment by dirk-thomas** [comment]
Closing in favor of #104.

**Pull request closed without merging**
